### PR TITLE
Add localization

### PR DESCRIPTION
**Pull request by pardoman**
## Description
Add localization feature to the app.
This PR is a rework of my previous PR #33 which is now closed (in favor of this one).

I'm creating this PR in draft mode (for now) because there are still a few issues to work around:
- [ ] Unique units and upgrades are not working
- [ ] Non-English tooltips are not working (because common.json files are missing for their locales).
- [ ] Python script hasn't been updated
- [ ] Localization UI buttons could use some work

### English - Aztecs
image

### Chinese - Aztecs
There are a few obvious issues here, still.
image

### CODE REVIEW

**Comment by lalitpatel** [comment]
I see that the regex to format the info boxes isn't working properly for non English locales. We may have to find some clever solution to that. Maybe format the info at the time of generating `data.json`?

**Comment by HSZemi** [comment]
Is that due to the string `Upgrades`? Do you even need that one in the regex, can't you just transform the string based on the `<i>` tags?

**Comment by lalitpatel** [comment]
I guess I can use that. I will have to filter buildings out of the regex as there are certain info texts (eg. Blacksmith) where there is text in italics. Will submit a pull request shortly.

image

**Comment by HSZemi** [comment]
That specific issue could be worked around by taking into account the `<b>` tags as well, but it's not pretty.

**Comment by pardoman** [comment]
I'll update this asap.

**Comment by lalitpatel** [comment]
I have couple of suggestions about how to place the language switcher (see image below).

1. We can either keep it on the top right if we chose it to be short switcher. 
2. Else put it at the bottom if we want a more descriptive one.

Sample code in [this branch](https://github.com/SiegeEngineers/aoe2techtree/compare/master...lalitpatel:language-switch?expand=1). 

positions

sample

**Comment by lalitpatel** [comment]
@pardoman let me know if you need any help from me to get this rolling.

**Comment by HSZemi** [comment]
We have a working language switcher now, so I am closing this pull request. Thank you again for putting in the effort and creating the base for it :yellow_heart:

**Pull request closed without merging**
