### PR TITLE
Added missing '%' character in Couman team bonus description (french).

### PR DESCRIPTION
**Pull request by blackbird806**

### CODE REVIEW

**Comment by simonsan** [comment]
I think these ones are generated from the game files. So fixing them in here is not the best way. You might want to open a thread in https://forums.ageofempires.com 

@happyleavesaoc should correct me if I'm wrong.

**Comment by simonsan** [comment]
Confused Repositories, what I said before was wrong. Sorry. :)

**Comment by HSZemi** [comment]
> Confused Repositories, what I said before was wrong. Sorry. :)

No, you were completely right, you just tagged the wrong person :wink: 

@blackbird806 The texts are taken directly from the game files, which means this is not an issue in aoe2techtree, but in the game files themselves. It would therefore be recommended to open a thread in [the Bugs section on forums.ageofempires.com](https://forums.ageofempires.com/c/age-of-empires-ii/aoe2-de-bugs/102) and report the issue there, so it can be fixed at the source.

Still, I appreciate that you took the time to report this bug here :slightly_smiling_face:

**Comment by blackbird806** [comment]
I wasn't sure if the files were generated or not so in doubt I submited the PR. I will raise the issue in the AOE forums. Thanks for looking at my PR =)

**Pull request closed without merging**
