### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by umutbalkan**
solves #40

### CODE REVIEW

**Comment by HSZemi** [comment]
Your solution has the slight disadvantage that it is no longer possible to close the info box.

**Comment by umutbalkan** [comment]
interesting... clicking on the edges between nodes or other svg elements closes it though

**Comment by HSZemi** [comment]
I hope fcabe8691673d933d74d1eb83923ab58e2e4becc resolves your issue :slightly_smiling_face:

**Comment by lalitpatel** [comment]
Hi @HSZemi this is indeed related to support for alpha in background fill color. Thanks to you and @umutbalkan for fixing this.

**Pull request closed without merging**
