### PR TITLE
Add civ logos

### PR DESCRIPTION
**Pull request by paulirish**
I've wanted these since I first started using this webapp. Figured I'd give it a shot.

----------

screenshots:

image
image

### CODE REVIEW

**Comment by HSZemi** [comment]
Very nice, thank you. Would it be possible to keep the civilisation name centred?

**Comment by paulirish** [comment]
sure. is this what you're looking for?

image

**Comment by HSZemi** [comment]
I think it is, thanks!

**Comment by HSZemi** [comment]
grafik
The civ icons do not load for me since it tries to load e. g. `Goths.png` but the file is called `goths.png`. 
To solve this, you could either rename the files accordingly, or add a `.toLowerCase()` at the right place. I would go with the renaming though.

**Comment by paulirish** [comment]
good call. :)

interesting that my personal local server is case insensitive. anyway, i'm glad you caught that!

**Comment by HSZemi** [comment]
Thanks a lot!

**Pull request merged**
