### PR TITLE
Updated many aspects

### PR DESCRIPTION
**Pull request by LOSER4ever**
1. Updated civ bonuses, UTs, TB descriptions to the best of my knowledge
2. Hid attack stats for units and buildings which cannot attack at all
3. Bug fix: Showed accuracy of units and buildings which have 100% accuracy
4. Solved the issue I created
5. and probably some more

Provide feedback for declined changes.

### CODE REVIEW

**Comment by HSZemi** [comment]
First of all, thank you for spending your time to improve aoe2techtree.

- The contents of `strings.json` are taken directly from the game files. We will never edit those unless we have a very, very good reason to, since it's just not feasible for us to maintain those edits across 17 localisations. Modifications to the game's strings file should therefore be suggested in the official Age of Empires forums.
- The contents of `data.json` are generated directly from the game's dat file. There cannot be a reason to edit the contents of that file manually since it literally represents the ground truth. If something is off, the reason is most likely in how we process and display that data. If you believe that the Town Center is missing attack values, you probably want to suggest to display the values of another one of the 20 Town Centers in the dat file.
- There is always a trade-off between showing all technical values and showing meaningful values. For example, we currently only display Accuracy values below 100 % in order to not display them for melee units (who have a 100 % default), but still display the 0 attack and accuracy values for buildings since they are technically there. Those are not bugs, but deliberate choices, however not necessarily the best choices that can be made. Your edit suggestions are a push into the "showing meaningful values" direction, and I can sympathize with that.

**Comment by LOSER4ever** [comment]
Oh yes, I forgot about melee units. I was thinking about Castles etc which have 100% accuracy, but that too is understandable. Some archer units like Genoese Crossbowmen have 100% accuracy too.

Next about Town Centers. Yes there are 20 something buildings for TCs, but the attack values don't come from there. All Town Centers have 5 base attack only but they never use that. Since TCs fire only when garrisioned by villagers or archers, the attack comes from secondary projectiles only. Every TC shares the same 2ndary projectile, whose attack values I have listed.

**Comment by LOSER4ever** [comment]
Based on your feedback, I removed accuracy for non-projectile melee units. It still shows accuracy for Mangonel-line, Throwing Axemen, Mamelukes, Gbetos and Chakram Throwers, which I thought was important because they are projectile attacks.

**Comment by HSZemi** [comment]
I integrated a refactored and slightly adapted version of the attack value display changes and other fixes.

It could be interesting in general to display projectile data, but one would probably have to come up with a good idea to display that data nicely.

**Comment by LOSER4ever** [comment]
Thanks for adapting my idea. I do notice that Accuracy is still shown for units/buildings which are unable to attack though.

**Comment by LOSER4ever** [comment]
I guess accuracy is left as it is for Monks.

**Pull request closed without merging**
