### PR TITLE
Proposal: New Favicon for the site

### PR DESCRIPTION
**Pull request by lalitpatel**
This icon better depicts a tech tree. The colors in the boxes are similar to the colors as that are used in the squares of the tech tree.

favicon

### CODE REVIEW

**Comment by HSZemi** [comment]
I am not against a new favicon per se (my beautiful tree! :sob: ), but I am not yet convinced by your proposal. Let's look at the two next to each other:
grafik
My perception is that the thick borders around the squares make it too dark in general. Maybe try a version without the borders?  
In addition, I guess that a brownish background would make it more recognizable. Could we try a version with a light brown background as well, maybe even not a flat colour, but with some noise like the HD background that we use?

**Comment by lalitpatel** [comment]
You suggestions make sense. I will give it a shot. I am a noob when it comes to graphic design. I can hardly draw anything other than geometric shapes 😄

**Comment by HSZemi** [comment]
Please do not stab the favicon, it has done nothing to harm you.

**Comment by HSZemi** [comment]
\*internal screaming\*
grafik
That would upset a lot of people if they knew :rofl:

**Comment by HSZemi** [comment]
grafik
grafik
Hmm… Which version do you prefer?

**Comment by lalitpatel** [comment]
I like the one with the brown background. Matches the over all theme.

**Comment by HSZemi** [comment]
Thank you :yellow_heart:

**Pull request merged**
