### PR TITLE
Add building index links to find things more easily. Scrolling is unweildy.

### PR DESCRIPTION
**Pull request by DerSaidin**

### CODE REVIEW

**Comment by HSZemi** [comment]
I must confess, my initial reaction was "what is this now", but I am sold. It is just such a simple and clear way to jump to what you want to look at. Even the position, while it once again increases the height of that sidebar, is the most fitting position in my opinion. Thank you for the proposal!

Two thoughts I have had:

1. Something along the lines of "Quick Navigation" might be a more suitable title for the panels. We might even remove the "Building Index" and "Key" titles completely and replace them with some thinner kind of separator, maybe a neatly styled `<hr>`. That would also solve the issue of collecting 16 translations for the title.
2. Would it be possible to center the tech tree on the building when clicking on the index, instead of aligning it on the left-most item under the building? One could also highlight the whole lane when navigating to the building. Somewhat like this: 
grafik

**Comment by simonsan** [comment]
Oh nice one!

**Comment by DerSaidin** [comment]
1) I swapped the title to a `<hr>`. I think this looks pretty neat with the existing style sheet.
The `margin-bottom: -20px;` feels a bit hacky, but it feels like wasted space without it.
I won't touch the "Key" in this commit. 

2) Centering done. This is nicer.
Highlighting might be nice, but I'm not going add that in this change.

I also cleaned up the constants.

**Comment by HSZemi** [comment]
Thank you! :yellow_heart: 
I have slightly adjusted your code in 5f7f72a79570321d6aa1c3c0fb5e1d3d8e386c3d and added the lane highlighting in a9b974f60dda5350931d43c7d1a1edf8ab209663

**Pull request closed without merging**
