### PR TITLE
FR translation fixes

### PR DESCRIPTION
**Pull request by blemaire**
This commit:
- removes the non-breaking spaces present in the french strings.json file
- fixes invalid translations
- fixes invalid civilization bonus

### CODE REVIEW

**Comment by blemaire** [comment]
Ok, removing non-breaking spaces was not a great idea, it broke too many things so I will revert that and only keep the bonus fixes and translations errors.
I will attempt to remove nbsp separately to prevent breaking changes

**Comment by HSZemi** [comment]
Hi, thanks for your contribution!

We are more or less blindly importing the official strings file from the game, since maintaining custom edits to various language files would not be manageable. You should therefore report those bugs in the french translation [in the official Age of Empires forums](https://forums.ageofempires.com/c/age-of-empires-ii/aoe2-de-bugs/102) in the hopes that they get fixed in the actual game.

The non-breaking spaces in front of colons seem to be in accordance with [french typographic rules](https://www.sciencespo.fr/ecole-doctorale/sites/sciencespo.fr.ecole-doctorale/files/CNRStypo.pdf).

**Comment by blemaire** [comment]
Thanks @HSZemi I will report the translations errors there.

Regarding the non-breaking spaces, they are inconsistent, that's why I attempted to remove them all but in fact we should be adding non-breaking spaces where relevant. Are these again taken from official string files and therefore have no power over those?

Thanks

**Comment by HSZemi** [comment]
> Are these again taken from official string files and therefore have no power over those?

All strings in our translations are taken from the official files. We could modify them, but as I explained, too much work to keep that up to date. Better push the devs to fix the game files directly.

**Pull request closed without merging**
