### PR TITLE
Add localization

### PR DESCRIPTION
**Pull request by nico2che**
one more try

thanks to @lalitpatel for the switcher and @pardoman for the data

Todo, after of during this PR
- [ ] translate hard strings on HTML
- [x] generate missing translations

### CODE REVIEW

**Comment by HSZemi** [comment]
Looks alright! Dark Age and Xolotl Warrior seem to be missing proper translations still, but that should be fixable.

There is an issue with the civ grid in the advanced stats though: Every time you switch the language, it gets longer :see_no_evil: 
grafik

**Comment by nico2che** [comment]
thx for your feedback, I fixed it by moving `createXRefBadges();` on init

I'll update my op with more details

**Comment by HSZemi** [comment]
Looks good! You should be able to run `scripts/generateDataFiles.py` to fix the missing strings in the language files.

I would say once those are updated we can merge this, and then think about whether we want to translate the tech tree specific strings in the extra stats as well, and if so, how.

**Comment by HSZemi** [comment]
I just ran the script again myself to update the data, and then merged this manually. Thank you for picking up this long-lived topic :yellow_heart:

**Comment by nico2che** [comment]
Thank you for your help, I didn't have access to the game to generate data

**Pull request closed without merging**
