### PR TITLE
Fix/de building ordering

### LINKED ISSUE #46: DE building ordering
Hi there, I noticed a few discrepancies in ordering between the Definitive Edition in-game tech tree and the site, most of which are due to differences between the DE and HD tech trees. 

- Blacksmith/Siege Workshop have moved to between the Stable and Dock, from between Town Center and University in HD.  Internal to this, Mangonels and Rams are reversed under Siege Workshop -- in both HD and DE they are consistent with their position in the building menus where Rams are on the left.

- The University is now between the Dock and Towers, instead of Blacksmith and Mining Camp in HD.

- The Wonder (and Feitoria on the Portuguese tree) are now between Town Center and Mining Camp instead of between Stable and Dock in HD.

- Krepost is found between Castle and Monastery on the Bulgarian tech tree, rather than between Stable and Dock, and it shows the Konnik as a buildable unit.

These are rather minor issues I know, but the Blacksmith/University ordering in particular really throw me off whenever I switch between the website and game trees.  I'd totally understand if you're keeping it this way to match HD Edition, however since the dataset is based on the latest version of DE, I figured consistency in alignment would make the most sense.  Anyway, love the site - keep up the good work!

### PR DESCRIPTION
**Pull request by MangelWare**
Resolves #46.

I am a quite frequent user of aoe2techtree.net, and therefore saw my chance to contribute when I found the issue.

For the reorderings, I moved the lane pushes in getDefaultTree() around.

I added the Konnik and Elite Konnik as permanent Carets under the Krepost, as unavailable unique units (e.g. Genitour) usually are not invisible (like in DE), but disabled. This also avoids any ID conflicts, as the Konnik and Elite Konnik are else only used with the `UNIQUE_UNIT` and `ELITE_UNIQUE_UNIT` ID respectively within the castle lane. Hope this is a reasonable solution.

Additionally to the mentioned issues, I found that the Farm is located to the right of the Mill Upgrades, opposing to the original DE Tech tree, where it is located inbetween the Market lane and the mentioned upgrades:

AoE2TechTree-Farm-Placement

I also changed this by moving the Farm lane accordingly.

Hope you are happy with the changes! Let me know if something could be done better!

### CODE REVIEW

**Comment by HSZemi** [comment]
Thank you for working on this!

There are three things that could still be addressed:

- The ordering on the units in the siege workshop (as mentioned in the original issue) has not been adapted yet
- The ordering of the techs in the monastery has been changed in DE as well
grafik
- The gold and stone mining camp upgrades have switched positions
grafik

**Comment by MangelWare** [comment]
Must have overlooked the Siege Workshop one in the issue. Will update all of the mentioned issues tomorrow.
Thanks for the instant feedback!

**Comment by MangelWare** [comment]
Done!

**Comment by HSZemi** [comment]
Marvellous, thank you! :yellow_heart:

**Pull request merged**
